const router = require("express").Router();
const { authenticate, authorize } = require("../middleware/auth");
const a = require("../controllers/adminController");
router.use(authenticate, authorize("admin"));
router.get("/dashboard", a.getDashboard);
router.get("/users", a.getUsers);
router.post("/users", a.createUserHandler);
router.put("/users/:id", a.updateUserHandler);
router.delete("/users/:id", a.deleteUserHandler);
router.get("/departments", a.getDepartmentsHandler);
router.post("/departments", a.createDepartmentHandler);
router.put("/departments/:id", a.updateDepartmentHandler);
router.delete("/departments/:id", a.deleteDepartmentHandler);
router.get("/departments/:id/trainers", a.getTrainersByDeptHandler);
router.get("/trainers", a.getAllTrainersHandler);
router.get("/programs", a.getProgramsHandler);
router.post("/programs", a.createProgramHandler);
router.put("/programs/:id", a.updateProgramHandler);
router.delete("/programs/:id", a.deleteProgramHandler);
router.get("/programs/:id/tree", a.getProgramTreeHandler);
router.get("/programs/:id/courses", a.getProgramCoursesHandler);
router.get("/programs/:id/sessions", a.getSessionsForProgramHandler);
router.post("/sessions", a.createSessionHandler);
router.get("/academic-levels", a.getAcademicLevelsHandler);
router.post("/academic-levels", a.createAcademicLevelHandler);
router.put("/academic-levels/:id", a.updateAcademicLevelHandler);
router.delete("/academic-levels/:id", a.deleteAcademicLevelHandler);
router.post("/courses", a.createCourseHandler);
router.put("/courses/:id", a.updateCourseHandler);
router.delete("/courses/:id", a.deleteCourseHandler);
router.put("/courses/:id/assign-trainer", a.assignTrainerHandler);
router.get("/certifications", a.getCertificationsHandler);
router.post("/certifications", a.createCertificationHandler);
router.put("/certifications/:id", a.updateCertificationHandler);
router.delete("/certifications/:id", a.deleteCertificationHandler);
router.put("/certifications/:id/assign-trainer", a.assignTrainerToCertHandler);
router.get("/rooms", a.getRoomsHandler);
router.post("/rooms", a.createRoomHandler);
router.put("/rooms/:id", a.updateRoomHandler);
router.delete("/rooms/:id", a.deleteRoomHandler);
router.get("/academic-years", a.getAcademicYearsHandler);
router.post("/academic-years", a.createAcademicYearHandler);
router.put('/academic-years/:id/set-active', a.setActiveAcademicYearHandler);
router.get("/semesters", a.getSemestersHandler);
router.get("/complaints", a.getComplaintsHandler);
router.put("/complaints/:id", a.updateComplaintHandler);
module.exports = router;