// FILE: src/api/index.js
import api from "./axiosInstance";

export const authApi = {
  login:          (body)   => api.post("/auth/login", body).then(r => r.data),
  selectRole:     (body)   => api.post("/auth/select-role", body).then(r => r.data),
  changePassword: (body)   => api.put("/auth/change-password", body).then(r => r.data),
  getMe:          ()       => api.get("/auth/me").then(r => r.data),
};

export const adminApi = {
  getDashboard:    ()      => api.get("/admin/dashboard").then(r => r.data),
  getUsers:        (p)     => api.get("/admin/users", { params: p }).then(r => r.data),
  createUser:      (b)     => api.post("/admin/users", b).then(r => r.data),
  updateUser:      (id,b)  => api.put(`/admin/users/${id}`, b).then(r => r.data),
  deleteUser:      (id)    => api.delete(`/admin/users/${id}`).then(r => r.data),
  getDepartments:  ()      => api.get("/admin/departments").then(r => r.data),
  createDepartment:(b)     => api.post("/admin/departments", b).then(r => r.data),
  updateDepartment:(id,b)  => api.put(`/admin/departments/${id}`, b).then(r => r.data),
  deleteDepartment:(id)    => api.delete(`/admin/departments/${id}`).then(r => r.data),
  getDeptTrainers: (id)    => api.get(`/admin/departments/${id}/trainers`).then(r => r.data),
  getPrograms:     ()      => api.get("/admin/programs").then(r => r.data),
  createProgram:   (b)     => api.post("/admin/programs", b).then(r => r.data),
  updateProgram:   (id,b)  => api.put(`/admin/programs/${id}`, b).then(r => r.data),
  deleteProgram:   (id)    => api.delete(`/admin/programs/${id}`).then(r => r.data),
  getProgramCourses:  (id)   => api.get(`/admin/programs/${id}/courses`).then(r => r.data),
  getProgramSessions: (id)   => api.get(`/admin/programs/${id}/sessions`).then(r => r.data),
  createSession:      (b)    => api.post("/admin/sessions", b).then(r => r.data),
  createCourse:       (b)    => api.post("/admin/courses", b).then(r => r.data),
  updateCourse:       (id,b) => api.put(`/admin/courses/${id}`, b).then(r => r.data),
  deleteCourse:       (id)   => api.delete(`/admin/courses/${id}`).then(r => r.data),
  assignTrainer:      (id,b) => api.put(`/admin/courses/${id}/assign-trainer`, b).then(r => r.data),
  getCertifications:      ()     => api.get("/admin/certifications").then(r => r.data),
  createCertification:    (b)    => api.post("/admin/certifications", b).then(r => r.data),
  updateCertification:    (id,b) => api.put(`/admin/certifications/${id}`, b).then(r => r.data),
  deleteCertification:    (id)   => api.delete(`/admin/certifications/${id}`).then(r => r.data),
  assignTrainerToCert:    (id,b) => api.put(`/admin/certifications/${id}/assign-trainer`, b).then(r => r.data),
  getRooms:        ()      => api.get("/admin/rooms").then(r => r.data),
  createRoom:      (b)     => api.post("/admin/rooms", b).then(r => r.data),
  updateRoom:      (id,b)  => api.put(`/admin/rooms/${id}`, b).then(r => r.data),
  deleteRoom:      (id)    => api.delete(`/admin/rooms/${id}`).then(r => r.data),
  getAcademicYears:  ()    => api.get("/admin/academic-years").then(r => r.data),
  createAcademicYear:(b)   => api.post("/admin/academic-years", b).then(r => r.data),
  getAcademicLevels: ()    => api.get("/admin/academic-levels").then(r => r.data),
  getSemesters:      ()    => api.get("/admin/semesters").then(r => r.data),
  getComplaints:     ()    => api.get("/admin/complaints").then(r => r.data),
  updateComplaint:   (id,b)=> api.put(`/admin/complaints/${id}`, b).then(r => r.data),
};

export const hodApi = {
  getDashboard:     ()     => api.get("/hod/dashboard").then(r => r.data),
  getPrograms:      ()     => api.get("/hod/programs").then(r => r.data),
  getWeeks:         ()     => api.get("/hod/weeks").then(r => r.data),
  createWeek:       (b)    => api.post("/hod/weeks", b).then(r => r.data),
  getPublishedWeeks:()     => api.get("/hod/weeks/published").then(r => r.data),
  publishWeek:      (id)   => api.put(`/hod/weeks/${id}/publish`).then(r => r.data),
  unpublishWeek:    (id)   => api.put(`/hod/weeks/${id}/unpublish`).then(r => r.data),
  deleteWeek:       (id)   => api.delete(`/hod/weeks/${id}`).then(r => r.data),
  getAvailability:  (p)    => api.get("/hod/availability", { params: p }).then(r => r.data),
  getLockStatus:    (weekId)=> api.get("/hod/availability/lock", { params: { weekId } }).then(r => r.data),
  lockAvailability: (b)    => api.post("/hod/availability/lock", b).then(r => r.data),
  unlockAvailability:(b)   => api.post("/hod/availability/unlock", b).then(r => r.data),
  generateTimetable:(b)    => api.post("/hod/timetable/generate", b).then(r => r.data),
  generateCertTimetable:(b)=> api.post("/hod/cert-timetable/generate", b).then(r => r.data),
  getTimetables:    ()     => api.get("/hod/timetables").then(r => r.data),
  publishTimetable: (id)   => api.put(`/hod/timetables/${id}/publish`).then(r => r.data),
  getAnnouncements: ()     => api.get("/hod/announcements").then(r => r.data),
  createAnnouncement:(b)   => api.post("/hod/announcements", b).then(r => r.data),
  deleteAnnouncement:(id)  => api.delete(`/hod/announcements/${id}`).then(r => r.data),
};

export const trainerApi = {
  getDashboard:      ()     => api.get("/trainer/dashboard").then(r => r.data),
  getCourses:        ()     => api.get("/trainer/courses").then(r => r.data),
  getCertifications: ()     => api.get("/trainer/certifications").then(r => r.data),
  getPublishedWeeks: ()     => api.get("/trainer/weeks/published").then(r => r.data),
  getAvailability:   (p)    => api.get("/trainer/availability", { params: p }).then(r => r.data),
  submitAvailability:(b)    => api.post("/trainer/availability", b).then(r => r.data),
  clearAvailability: (weekId)=> api.delete(`/trainer/availability/${weekId}`).then(r => r.data),
  getTimetable:      (p)    => api.get("/trainer/timetable", { params: p }).then(r => r.data),
  getGrades:         ()     => api.get("/trainer/grades").then(r => r.data),
  upsertGrade:       (b)    => api.post("/trainer/grades", b).then(r => r.data),
  getComplaints:     ()     => api.get("/trainer/complaints").then(r => r.data),
  respondComplaint:  (id,b) => api.put(`/trainer/complaints/${id}`, b).then(r => r.data),
  getAnnouncements:  ()     => api.get("/trainer/announcements").then(r => r.data),
};

export const studentApi = {
  getDashboard:           ()    => api.get("/student/dashboard").then(r => r.data),
  getTimetable:           (p)   => api.get("/student/timetable", { params: p }).then(r => r.data),
  getCertTimetable:       (p)   => api.get("/student/cert-timetable", { params: p }).then(r => r.data),
  getCertEnrollments:     ()    => api.get("/student/cert-enrollments").then(r => r.data),
  getPublishedWeeks:      ()    => api.get("/student/weeks/published").then(r => r.data),
  getCertAvailability:    (p)   => api.get("/student/cert-availability", { params: p }).then(r => r.data),
  submitCertAvailability: (b)   => api.post("/student/cert-availability", b).then(r => r.data),
  getGrades:              ()    => api.get("/student/grades").then(r => r.data),
  getComplaints:          ()    => api.get("/student/complaints").then(r => r.data),
  createComplaint:        (b)   => api.post("/student/complaints", b).then(r => r.data),
  getAnnouncements:       ()    => api.get("/student/announcements").then(r => r.data),
};

export const parentApi = {
  getDashboard:     ()           => api.get("/parent/dashboard").then(r => r.data),
  getChildren:      ()           => api.get("/parent/children").then(r => r.data),
  getChildTimetable:(id,p)       => api.get(`/parent/children/${id}/timetable`, { params: p }).then(r => r.data),
  getChildGrades:   (id)         => api.get(`/parent/children/${id}/grades`).then(r => r.data),
  getComplaints:    ()           => api.get("/parent/complaints").then(r => r.data),
  createComplaint:  (b)          => api.post("/parent/complaints", b).then(r => r.data),
  getAnnouncements: ()           => api.get("/parent/announcements").then(r => r.data),
};

export const secretaryApi = {
  getDashboard:      ()    => api.get("/secretary/dashboard").then(r => r.data),
  getStudents:       ()    => api.get("/secretary/students").then(r => r.data),
  registerStudent:   (b)   => api.post("/secretary/students", b).then(r => r.data),
  updateStudent:     (id,b)=> api.put(`/secretary/students/${id}`, b).then(r => r.data),
  getPrograms:       (p)   => api.get("/secretary/programs", { params: p }).then(r => r.data),
  getCertifications: ()    => api.get("/secretary/certifications").then(r => r.data),
  getDepartments:    ()    => api.get("/secretary/departments").then(r => r.data),
};
